Repository jenkinsci/checkmarx-ast-scanner-plugin, pull requests merged in 2022-04, with the labels that each got.

#36 Refactoring and Code Cleanup for Tests.
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  pom.xml
  src/test/java/com/checkmarx/jenkins/CheckmarxScanBuilderDescriptorTest.java
  src/test/java/com/checkmarx/jenkins/CheckmarxScanBuilderTest.java
  src/test/java/com/checkmarx/jenkins/CheckmarxScanPipelineTest.java
  src/test/java/com/checkmarx/jenkins/CheckmarxTestBase.java
  src/test/java/com/checkmarx/jenkins/utils/Constants.java
Labels: dependencies, chore

#29 Use Eclipse Temurin, not AdoptOpenJDK in action
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: chore

#46 update base release
  pom.xml
Labels: bug, enhancement
