Repository jenkinsci/checkmarx-ast-scanner-plugin, pull requests merged in 2024-05, with the labels that each got.

#284 AST-41922 fix the installer to get the envVars from the Jenkins object
  src/main/java/com/checkmarx/jenkins/tools/CheckmarxInstaller.java
  src/main/java/com/checkmarx/jenkins/tools/ProxyHttpClient.java
Labels: bug

#285 AST-40305 Upgrade jenkins version from 2.375 to 2.375.4
  pom.xml
Labels: documentation, enhancement, dependencies

#288 Jenkins | Upgrade Java-Wrapper version AST-41951
  pom.xml
Labels: enhancement, dependencies

#290 Update wrapper to cli 2.1.2 AST-43187
  pom.xml
Labels: bug, dependencies
